### ISSUE TITLE
Hopefully the last panic

### ISSUE THREAD

**Issue by manfredlotz** [J-F-Liu/lopdf#43] opened 2018-10-10 11:50 UTC
This document https://www.uspsoig.gov/sites/default/files/document-library-files/2016/RARC-WP-16-001.pdf

gives:

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("corrupt deflate stream") }', libcore/result.rs:945:5

**Comment by manfredlotz** [comment] 2018-10-17 17:05
I understand. However, as PDF viewers are happy when loading the document what should be the solution.

Perhaps lopdf should have a 'relaxed' option where such oddities are handled gracefully (i.e no panic, only a warning or so). Not sure.

**Comment by J-F-Liu** [comment] 2018-10-24 04:09
This file is encrypted, so decryption is needed before decompress.

**Comment by manfredlotz** [comment] 2018-10-25 03:49
Do you plan to implement it?

**Comment by J-F-Liu** [comment] 2018-10-25 05:52
Yes, but not high priority, maybe in 2019.

**Comment by Heinenen** [comment] 2024-08-03 16:18
I think decryption is implemented now, and the issue should no longer occur.
Since the document is no longer available, I can't verify that the issue is indeed fixed.

I would suggest closing this issue.

**Closed** 2024-08-07 08:02 UTC
