### ISSUE TITLE
http://www.faithaliveresources.org/Content/Site135/FilesSamples/105315400440pdf_00000009843.pdf does not load 

### ISSUE THREAD

**Issue by jrmuizel** [J-F-Liu/lopdf#27] opened 2018-06-05 19:18 UTC
It gives: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: StringError("corrupt deflate stream") }', libcore/result.rs:945:5

**Comment by J-F-Liu** [comment] 2018-06-06 03:53
The error is from decoding 359 0 obj, need to confirm whether is stream content is valid deflate stream or not.

**Comment by J-F-Liu** [comment] 2018-10-24 14:52
Duplicate of #43

**Closed by J-F-Liu** 2018-10-24 14:52 UTC
Labels: Encryption
