### ISSUE TITLE
ToUnicode CMap error with 0.34.0

### ISSUE THREAD

**Issue by honuonhval** [J-F-Liu/lopdf#319] opened 2024-09-04 08:05 UTC
Not exactly sure what has changed since 0.32.0 (last version I used and worked) but some of my pdfs are now giving me error.
pdf in question - https://arxiv.org/pdf/2312.16171 - there are others but this one is publicly available.

```
thread 'tokio-runtime-worker' panicked at src/reporting/document.rs:39:40:
called `Result::unwrap()` on an `Err` value: Generic("ToUnicode CMap error: Could not parse ToUnicodeCMap: Error!"
```
If you need any other information, I can provide more.

**Comment by Heinenen** [comment] 2024-09-04 11:06
#314 is probably what causes this. Before this PR the UnicodeCmap was simply ignored.
cc @dkaluza

**Comment by dkaluza** [comment] 2024-09-05 22:34
Indeed it looks like majority of text in this pdf was properly extracted in previous version.

Current problem is probably caused by the fact that some fonts in this document have 1 byte ranges in the ToUnicode cmap specified and current implementation is limited to 2 bytes ranges.

I will try to look into this next week.

At the first sight I see that there are also 'differences' encoding in this pdf that as far as I know are not treated correctly in neither version.

**Comment by vootooguru** [comment] 2024-09-14 10:40
This issue seems to be widespread, with users having problems dealing with PDF files using TrueType fonts while others who are working with Type1 fonts seem to have no issues. It's likely related to the specific behavior of the software or library you're using when dealing with these font formats. Please provide more context if possible so that a more accurate solution can be provided.

**Comment by dkaluza** [comment] 2024-09-14 18:19
I have just submitted a draft PR that solves the issue for the indicated PDF.
It is in draft as **pom parser changes are still missing**.

Generally it contains:
- changes in parsing, so that it shouldn't fail when there are comments in the Cmap section
- changes parsing so that it allows variadic source codes from 1 to 4 bytes
- handles decoding of text written with fonts that have source codes in ToUnicode CMap ranging from 1 byte to 4 bytes.

You can preview it on my fork if you wish. https://github.com/dkaluza/lopdf/tree/var-len-unicode-cmap
I have also tested it on TrueType fonts pdf from #125 that was not working previously and now it parses just fine.

**Comment by vootooguru** [comment] 2024-09-15 05:09
> 我刚刚提交了一份 PR 草案，解决了指定 PDF 的问题。它处于草稿阶段，因为 **pom 解析器更改仍然缺失**。
> 
> 通常它包含：
> 
> * 解析中的更改，以便在 Cmap 部分有注释时它不会失败
> * 更改解析，以便允许 1 到 4 字节的可变参数源代码
> * 处理使用在 ToUnicode CMap 中具有 1 字节到 4 字节的源代码的字体编写的文本的解码。
> 
> 如果你愿意，你可以在我的 fork 上预览它。https://github.com/dkaluza/lopdf/tree/var-len-unicode-cmap 我还在 #125 的 TrueType 字体 pdf 上对其进行了测试，该字体以前不起作用，现在它可以很好地解析。
> 
> 如果您对某些 pdf 仍有问题，请告诉我，以便我进行调查。
> 
> 我不确定我是否正确理解了你的评论。 PDF 解析在 lopdf 库中处理。据我所知，代码不使用任何外部 PDF 解析器。

Okay, I'll try it and results will be feedback.

**Comment by vootooguru** [comment] 2024-09-15 05:23
> > 我刚刚提交了一份 PR 草案，解决了指定 PDF 的问题。它处于草稿阶段，因为 **pom 解析器更改仍然缺失**。
> > 通常它包含：
> > 
> > * 解析中的更改，以便在 Cmap 部分有注释时它不会失败
> > * 更改解析，以便允许 1 到 4 字节的可变参数源代码
> > * 处理使用在 ToUnicode CMap 中具有 1 字节到 4 字节的源代码的字体编写的文本的解码。
> > 
> > 如果你愿意，你可以在我的 fork 上预览它。https://github.com/dkaluza/lopdf/tree/var-len-unicode-cmap 我还在 #125 的 TrueType 字体 pdf 上对其进行了测试，该字体以前不起作用，现在它可以很好地解析。
> > 如果您对某些 pdf 仍有问题，请告诉我，以便我进行调查。
> > 我不确定我是否正确理解了你的评论。 PDF 解析在 lopdf 库中处理。据我所知，代码不使用任何外部 PDF 解析器。
> 
> Okay, I'll try it and results will be feedback.

 I tried your modified version, running cargo run --example extract_text --features="serde" d:/testdata/test.pdf, and the output file shows many errors like ToUnicodeCMap(ParseError). I uploaded the original file so you can easily reproduce this issue.
[test.pdf](https://github.com/user-attachments/files/17004713/test.pdf)

**Comment by dkaluza** [comment] 2024-09-15 08:49
@vootooguru I have looked into this pdf.

Unfortunately it is not conforming to the PDF specification.
The CMapName are missing a leading slash which is required according to the spec.
Below an example of the ToUnicode stream:
```
b"/CIDInit /ProcSet findresource begin
12 dict begin
begincmap
/CMapName SimSun-cmap def
/CMapType 2 def
/CIDSystemInfo <<
/Registry (Adobe)
/Ordering (UCS)
/Supplement 0
>> def
1 begincodespacerange
<0000> <FFFF>
endcodespacerange
2 beginbfchar
<01c2> <3000>
<01c3> <3001>
endbfchar
5 beginbfchar
<047b> <4e4b>
<047c> <4e4c>
<047d> <4e4d>
<047e> <4e4e>
<047f> <4e4f>
endbfchar
endcmap
CMapName currentdict /CMap defineresource pop
end
end";
```
(I have changed the beginbfchar sections to make it small, but left the rest intact)

As this is not compliant with the standard (the name should be /SimSun-cmap as far as I know) I'm afraid we should not introduce a change to the main repository and probably should be fixed by the tool creating the pdf that you have uploaded. (This should be the decision of the maintainers I do not have the power to make decisions here) 

Nevertheless as I have created the code to properly parse this document to test that this is indeed an issue, feel free to use it on your fork.  [patch_name_without_slash_diff.txt](https://github.com/user-attachments/files/17005115/patch_name_without_slash_diff.txt)

**Comment by vootooguru** [comment] 2024-09-15 13:52
> @vootooguru I have looked into this pdf.
> 
> Unfortunately it is not conforming to the PDF specification.
> The CMapName are missing a leading slash which is required according to the spec.
> Below an example of the ToUnicode stream:
> ```
> b"/CIDInit /ProcSet findresource begin
> 12 dict begin
> begincmap
> /CMapName SimSun-cmap def
> /CMapType 2 def
> /CIDSystemInfo <<
> /Registry (Adobe)
> /Ordering (UCS)
> /Supplement 0
> >> def
> 1 begincodespacerange
> <0000> <FFFF>
> endcodespacerange
> 2 beginbfchar
> <01c2> <3000>
> <01c3> <3001>
> endbfchar
> 5 beginbfchar
> <047b> <4e4b>
> <047c> <4e4c>
> <047d> <4e4d>
> <047e> <4e4e>
> <047f> <4e4f>
> endbfchar
> endcmap
> CMapName currentdict /CMap defineresource pop
> end
> end";
> ```
> (I have changed the beginbfchar sections to make it small, but left the rest intact)
> 
> As this is not compliant with the standard (the name should be /SimSun-cmap as far as I know) I'm afraid we should not introduce a change to the main repository and probably should be fixed by the tool creating the pdf that you have uploaded. (This should be the decision of the maintainers I do not have the power to make decisions here) 
> 
> Nevertheless as I have created the code to properly parse this document to test that this is indeed an issue, feel free to use it on your fork.  [patch_name_without_slash_diff.txt](https://github.com/user-attachments/files/17005115/patch_name_without_slash_diff.txt)
> 
> 
> 

OK, I understand. This is one of some PDFs that I used for testing. I happened to use it when testing lopdf. I don't know the PDF specification. Since this file can be opened with a reader, I mistakenly thought this might be a problem with lopdf. It's good to figure it out. Thank you for your patient reply and the patch you made. Thank you very much.

**Comment by dkaluza** [comment] 2024-09-15 16:50
No problem, I'm also do not have a huge experience with specification, I'm just reading it when needed.
Anyway thanks for submitting this problematic pdf.

It would be good to have a more robust error messaged informing which part of the document has not been properly parsed, e.g. the CMapName here, but this is a subject for another issue

 I think many readers try to be bullet proof and allow many divergences from the spec. I do not know how does lopdf approach this, it would be good to hear from the maintainers.

**Comment by vootooguru** [comment] 2024-09-16 08:07
Yes, I am also very surprised that the reader can parse this document while lopdf cannot. I believe that end users will also have this feeling. If I need to provide other information that is helpful for solving this problem, I will be happy to help.

**Comment by Heinenen** [comment] 2024-09-16 19:08
Since most PDF viewers try to accept PDF files which do not adhere to the spec, many writers don't do so either.
This creates this weird situation where implementing the spec isn't enough anymore, which we see here.

As for the state in lopdf: a relaxed parsing mode has been requested in #41, but isn't implemented.

**Closed** 2024-09-26 04:04 UTC
