### ISSUE TITLE
it seems not get all decoded elements while reading a pdf generated by ghostscript 9.27

### ISSUE THREAD

**Issue by BXHlixiaodong** [J-F-Liu/lopdf#221] opened 2023-03-17 07:27 UTC
Hi all.

I got a pdf generated by ghostscript on debian buster. I tried to parsing its page contents:

```rust
let mut doc = Document::load("./test04.pdf")?;
let page_content_ids: Vec<ObjectId> = doc
    .page_iter()
    .flat_map(|page_id| doc.get_page_contents(page_id))
    .collect();

for id in page_content_ids.into_iter() {
    let stream = doc.get_object_mut(id)?.as_stream_mut()?;
    stream.decompress();

    let content = stream.decode_content()?;

    content
        .operations
        .iter()
        .for_each(|op| println!("{:?}", op));    // here print all operators
    stream.set_content(content.encode()?); // also boxed into stream, nothing changed
    stream.compress()?;
}
doc.save("./test04.output.pdf)?;  // saved as other pdf file
```

here is the [test04.pdf](https://github.com/BXHlixiaodong/attachment/blob/main/test04.pdf).

I found no `Tj` operator from stdout, and the `test04.output.pdf` lose some elements, `test04.output.pdf` is not the same with `test04.pdf`.

Does anyone know how to fix it? or should I use other methods base on `Stream` or `Object`?
Thanks.

**Comment by Heinenen** [comment] 2024-11-18 23:36
You don't see a `Tj` operator because the PDF you provided doesn't contain one. It seems that the PDF is solely made up of images (of text).

That `test04.output.pdf` differs from the original is probably due to #78.

**Comment by Heinenen** [comment] 2024-11-24 22:15
I confirmed that the issue here are inline images. Closing as a duplicate of #78.

**Closed by Heinenen** 2024-11-24 22:15 UTC
